spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 720000
      maximumPoolSize: 5
      minimumIdle: 2
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  application:
    name: notification-svc

#service name for EKS routing
server:
  port: 7000
  servlet:
    contextPath: /notification-svc

#actuators properties
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  health:
    defaults:
      enabled: 'false'
