logging:
    level:
        org:
            hibernate: INFO
            springframework:
                web: INFO
        root: INFO
management:
    endpoints:
        health:
            show-details: always
        web:
            exposure:
                include: '*'
server:
    servlet:
        contextPath: /awardsevents
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 30000
            maxLifetime: 720000
            maximumPoolSize: 5
            minimumIdle: 2
        initialization-mode: always
        platform: postgres
    flyway:
        baseline-on-migrate: true
        enabled: true
        locations: classpath:db/migration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
    profiles:
        active: dev
